branch: main
branches:
  - "+([1-9])?(.{+([1-9]),x}).x"
  - main
  - next
  - name: alpha
    prerelease: true
  - name: beta
    prerelease: true
ci: false
dryRun: false
debug: false
extends: "semantic-release-npm-github-publish"
